### ISSUE TITLE
ConsolePlayerTest

### ISSUE THREAD

**Issue by kinshuk-kotecha** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#5]
In the ConsolePlayerTest, the test inputs c3->c2 and checks if the nextMove() method returns Move(2, 2, 2, 1). However, isn't this an invalid move for a knight on a 3x3 gameboard? Shouldn't the nextMove() method reject this input and ask for another one?

**Comment by Troublor** [comment]
In the test, we use `MockPiece` instead of `Knight`. In the implementation of `nextMove()` you should have no knowledge of the type of each piece. That is why we use the abstract class `Piece`. 

The validity of moves should be ensured in the `getAvailableMoves()` of each piece object. The `availableMoves` parameter of `nextMove()` should contain all available, valid moves. You can check if user input move is contained in `availableMoves` to ensure it is valid.

**Comment by kinshuk-kotecha** [comment]
Got it. Thanks!
